index.html

Tiny tweak to close #82.  
I've added the lead class to the paragraph as I think it's appropriate, but feel free to nix it if you disagree.

82 Update copy on about page

---

templates/eventCards.handlebars
templates/eventTableRow.handlebars

- Added event name to the table
- Added event name to the event cards
- Added links and RSVP links to the event cards
- issue #94

added event name to table and cards, added links and rsvp to cards

---

index.html
scripts/views/eventView.js

This closes #78 by adding a contact form.
Tech support tickets will be sent to `techsupport@` and will include browser and OS info (user entered, not auto).  All other tickets will be sent to `info@`.
_In all cases you should be able to respond to the person submitting the ticket by simply replying to the email._
Email code is live, so submitting the form on the test branch should properly email both addresses.  __Please test that it does!__
Here is the script triggering the emails, for prosperity:
```
function sendFormByEmail(event) 
{ 
var email = "info@THP"; // change this to the full email
var sheet = SpreadsheetApp.getActiveSheet();
var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
var senderEmail = event.namedValues[headers[1]].toString();
var senderName = …
```

#78 contact form

---

index.html
scripts/models/event.js

Closes issue #122, just want to double check on coffee events.

#122 dc events

---

index.html
scripts/models/event.js
scripts/views/eventView.js

Issue #124 
Added all to both Party dropdown and Event type dropdown. 
Selecting all removes the filters for that category.

124 all option

---

README.md

@DylanMoriarty I started with info on the API. I'm not sure what specific problems people are having though. Could you look this over and suggest other things folks might find helpful in the readme?

Added info on how to get started with Firebase.

---

index.html

143 text tweak

---

index.html
scripts/views/eventView.js

Two tiny tweaks.
Closes #152 and closes #164.

#152 #164 quick tweaks

---

index.html

Updated with "NextGen America" and link on About page - issue #175

#175 NextGen America update on About page

---

index.html
scripts/views/eventView.js

should have fixed this before. Banner is only shown on the home page

hide missing members banner on results page

---

index.html

This closes #193.  Tiny tweak to update meta tags with our new description.

193 Update meta description

---

scripts/views/map-walkthrough.md

Added it to scripts/views. Maybe there's a more appropriate place for it?

Add map walkthrough md file to the repo

---

Gruntfile.js
index.html
styles/customboot.less
templates/representativeCard.handlebars

This closes #166.
Right now it looks like some of the new fields (ahca and swingleft) aren't showing up for all results so I'm hiding those without info.

#166 add internal moc fields to cards

---

index.html
scripts/views/eventView.js
styles/customboot.less

#147 call to action when no events

---

scripts/views/emailSignUpView.js

This functions name got changed and broke the email signup.

fixed function call name

---

index.html
package-lock.json
package.json
scripts/controllers/state-routes.js
scripts/views/mapView.js
scripts/views/noWebGlMap.js
scripts/views/stateView.js

Redid the state routes because the original had massive conflicts with upstream master

Rerouting states

---

index.html
styles/bootstrap.4.utilities.less
styles/customboot.less

This closes #227.
I've also added a few of the helper utilities from bootstrap 4 (the width/margin/padding classes).

#227 add faq section

---

scripts/views/repCardView.js
templates/representativeCard.handlebars

References #238 but does not close it.
Super tiny change here.  We still need to add the `taxBill` field to the MoC objects on the backend and import the data.

238 Tiny change to add the tax bill vote to MoC cards

---

index.html
scripts/controllers/state-controller.js
scripts/controllers/state-routes.js
scripts/lib/urlParams.js
scripts/views/eventView.js
scripts/views/mapView.js
scripts/views/noWebGlMap.js
scripts/views/stateView.js
scripts/views/tableView.js
templates.js

This is building off of Reagan's PR. I moved some of the code to a controller so we have less nested if/else statements. And added padding around the state bounding boxes.

Filtering by state

---

scripts/controllers/map-controller.js
scripts/controllers/routes.js
scripts/views/mapboxView.js

added the district listener initiation to the routes

district listener is only on federal map

---

index.html
scripts/controllers/index-controller.js
scripts/views/indexView.js
scripts/views/stateView.js
styles/customboot.less

This closes #287 and cleans up the mobile nav menu while we're at it.

#287 state dropdown

---

index.html
package-lock.json
styles/customboot.less
templates/missingMemberCard.handlebars

#281 
Added Voted for GOP Tax Bill to Missing Members page on member cards and as a filter at the top of the page, replacing Member of section to keep cards from getting misaligned

Issue 281 tax votes to mm

---

index.html
scripts/views/repCardView.js
styles/customboot.less
templates/missingMemberCard.handlebars
templates/representativeCard.handlebars

This closes #304.
Please test the MoC cards (after a zip code search) as well as the missing member MoC cards.

#304 missing member poster

---

package-lock.json
scripts/views/mapView.js
scripts/views/tableView.js

Issue #300 & Observed behavior where switching between states kept the previous state events in the table view.
Now using the SortBy Date button sorts events by dateObj filter in database. In most cases this doesn't look like anything because they are sorted that way by default, but it doesn't bring up the Federal options instead anymore

State table switching states

---

index.html
package-lock.json
scripts/views/mapView.js
scripts/views/tableView.js

Issue #274 
Moved the section for no events up above the map and fixed a small typo in the text

Issue 274 move no events message

---

index.html
scripts/controllers/index-controller.js
scripts/controllers/map-controller.js
scripts/models/TownHall.js
scripts/views/eventView.js
scripts/views/googleMapView.js
scripts/views/mapView.js
scripts/views/mapboxView.js
scripts/views/tableView.js

This closes #356, #352, #348, and generally I tested a lot of clicking back and forth between state/federal, sorting, filtering etc and tried to make sure nothing was getting out of sync.

Data handeling fixes

---

index.html

Tiny pr to add a link to the pledge page and close #362.  Please test in mobile and desktop.

362 Add link to pledge page

---

scripts/views/mapboxView.js

Tiny tweak to re-enable mouse zoom and close #355.

355 Re-enable scrool to zoom

---

index.html

#385 
#318 (name changes from that issue)
This PR adds team bios for Jenita and Robert and removes Juliana

update bio section

---

index.html
src/index.html

update small changes to index html page in src/ folder, to keep consistent with current dev repo
todo:
add images for oregon state legislature

update index.html - same as dev

---

mapEmbed.html

#413 'Find A Town Hall' --> 'Find An Event'

update button type of mapEmbed

---

templates/eventModal.handlebars

#428 update "Okay" in RSVP copy

update RSVP copy

---

styles/customboot.less
templates/eventCards.handlebars
templates/eventTableRow.handlebars

fix current spacing issues with ada

Ada access

---

index.html
mapEmbed.html

More details for this commit here: https://github.com/townhallproject/townHallProject/issues/474

474 - NextGen/Indivisible edits

---

index.html

Swapped Nevada and North Carolina in Nav Bar

---

index.html

Addressed Issue #468 to change map legend icon name
- H.R.1 -> Voting Rights
- Youth Vote Town Hall -> Youth Vote

Change map legend icon name 

---

database.rules.json
index.html

Updated who-are-you section

---

.gitignore
database.rules.json
index.html
package-lock.json
package.json
scripts/views/tableView.js

Addressed Issue #513. 
Add Voting Rights and Youth Vote to dropdown filter & set them as default view.

Table default filter

---

index.html

Search by member field is hidden (in class), referring to issue #486

Member Search Field Hidden #486

---

index.html

#423 
This update fixes the donate link

update donate link

---

database.rules.json
index.html
scripts/models/MemberOfCongress.js
scripts/views/missingMembersView.js
scripts/views/tableView.js
styles/customboot.less
templates/missingMemberCard.handlebars

This re enables the missing members page for the 116th congress

missing members reenabled

---

styles/customboot.less

this PR addresses #534 
Update navbar breakpoint to avoid bad spacing 
-state nav buttons no longer cover other navigation buttons

update nav breakpoint to fix spacing issue (state hover covering other btns)

---

database.rules.json
index.html
mapEmbed.html

updating metadata description
#556

update metadata copy

---

functions/package.json
index.html

New report

---

index.html

hide infographic

---

src/templates/representativeCard.js

This PR clears the "Voted for Trump Tax Bill" and AHCA text on bottom of rep cards

clear rep card text from bottom

---

src/scripts/views/emailSignUpView.js
src/scripts/views/eventView.js

**Issue #595** 
Please let me know if I need to change it someway or anything else I am missing on this. I will be very grateful!
Thank you in advance,
Lidia

595: Solve bug with 'update email subscription' button not working

---

src/styles/customboot.less

Fixes navbar bug by changing tab-content > active style to 'contents'
• tested on each page change

fix nav bug - tab content active style

---

src/components/Header/index.js
src/components/Header/style.less

adds red background and button styling to donate button

Update donate button styling

---

package-lock.json
src/components/Header/index.js

Change "Donate" top heading to "Donate Now".

Submission for issue #597 

---

src/components/Home/EventsTable/style.less
src/styles/customboot.less

Added top margin to footer and bottom border to last child ant-list-item on home page because there was no bottom border once we added margin between table and footer

Issue #657 with @crashley1992 

---

src/components/Home/EventsTable/index.jsx
src/components/Home/EventsWarningBanner/index.jsx
src/components/Home/EventsWarningBanner/style.less

Created public health warning banner for events table. 
@nathanmwilliams @meganrm

Public health warning banner for events

---

src/scripts/models/MemberOfCongress.js

Description
Please include a summary of the change and which issue is fixed. Please also include relevant context. List any dependencies that are required for this change.
Fixes # (issue) 
Visual Change? If yes 
[ ] Attached before screenshots
[ ] Attached after screenshots
[ ] Mention @ nathanmwilliams

filtering out members not in office
